version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: dox
    main: ./main.go
    binary: dox
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ldflags:
      - -s -w -X github.com/stavros/dox/internal/cli.version={{.Version}}
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - id: dox
    builds:
      - dox
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README*

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"

release:
  target_commitish: master
  github:
    owner: stavros
    name: dox
  draft: false
  prerelease: auto
  mode: append
  footer: |
    ---
    **Full Changelog**: https://github.com/stavros/dox/compare/{{ .PreviousTag }}...{{ .Tag }}