name: Release Please

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: release-please-action
        uses: googleapis/release-please-action@v4.2.0
        with:
          release-type: go
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}